#!/bin/bash

source "$CONFIG_DIR/colors.sh"

ITEMS_DIR="$CONFIG_DIR/items" 
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=30 blur_radius=30 color=$BAR_COLOR corner_radius=5

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15:0"
  label.font="SF Pro:Semibold:15:0"
  icon.color=$WHITE 
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR       
  background.corner_radius=6            
  background.height=25                  
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  label.font.size=8
)
sketchybar --default "${default[@]}"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}":
    icon.padding_left=7
    icon.padding_right=7
    background.color=0x40ffffff
    background.corner_radius=5
    background.height=25                
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    # click_script="yabai -m space --focus $sid"
  )
  # sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done
source $ITEMS_DIR/time.sh
source $ITEMS_DIR/volume.sh
source $ITEMS_DIR/battery.sh
source $ITEMS_DIR/cpu.sh
# source $ITEMS_DIR/media.sh
source $ITEMS_DIR/ethernet.sh
source $ITEMS_DIR/front_app.sh
source $ITEMS_DIR/spaces.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
